# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RESTool/ui/design_v2.ui'
#
# Created: Sat May 16 15:44:18 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(583, 482)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.MainTabWidget.setObjectName(_fromUtf8("MainTabWidget"))
        self.BackupRestoreMigrateTab = QtGui.QWidget()
        self.BackupRestoreMigrateTab.setObjectName(_fromUtf8("BackupRestoreMigrateTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.BackupRestoreMigrateTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MainContentLayout = QtGui.QVBoxLayout()
        self.MainContentLayout.setObjectName(_fromUtf8("MainContentLayout"))
        self.BrowseerPickerLayout = QtGui.QHBoxLayout()
        self.BrowseerPickerLayout.setObjectName(_fromUtf8("BrowseerPickerLayout"))
        self.FirstBrowserLayout = QtGui.QHBoxLayout()
        self.FirstBrowserLayout.setSpacing(0)
        self.FirstBrowserLayout.setObjectName(_fromUtf8("FirstBrowserLayout"))
        self.FirstBrowserVerticalLayout = QtGui.QVBoxLayout()
        self.FirstBrowserVerticalLayout.setSpacing(0)
        self.FirstBrowserVerticalLayout.setObjectName(_fromUtf8("FirstBrowserVerticalLayout"))
        self.StaticFirstBrowserLabel = QtGui.QLabel(self.BackupRestoreMigrateTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.StaticFirstBrowserLabel.setFont(font)
        self.StaticFirstBrowserLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StaticFirstBrowserLabel.setObjectName(_fromUtf8("StaticFirstBrowserLabel"))
        self.FirstBrowserVerticalLayout.addWidget(self.StaticFirstBrowserLabel)
        self.FirstBrowserNameLayout = QtGui.QHBoxLayout()
        self.FirstBrowserNameLayout.setObjectName(_fromUtf8("FirstBrowserNameLayout"))
        self.StaticBrowserName = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticBrowserName.setObjectName(_fromUtf8("StaticBrowserName"))
        self.FirstBrowserNameLayout.addWidget(self.StaticBrowserName)
        self.cboFirstBrowser = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboFirstBrowser.setObjectName(_fromUtf8("cboFirstBrowser"))
        self.FirstBrowserNameLayout.addWidget(self.cboFirstBrowser)
        self.FirstBrowserNameLayout.setStretch(0, 40)
        self.FirstBrowserNameLayout.setStretch(1, 60)
        self.FirstBrowserVerticalLayout.addLayout(self.FirstBrowserNameLayout)
        self.FirstBrowserProfileLayout = QtGui.QHBoxLayout()
        self.FirstBrowserProfileLayout.setObjectName(_fromUtf8("FirstBrowserProfileLayout"))
        self.StaticProfileName = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticProfileName.setObjectName(_fromUtf8("StaticProfileName"))
        self.FirstBrowserProfileLayout.addWidget(self.StaticProfileName)
        self.cboFirstBrowserProfile = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboFirstBrowserProfile.setObjectName(_fromUtf8("cboFirstBrowserProfile"))
        self.FirstBrowserProfileLayout.addWidget(self.cboFirstBrowserProfile)
        self.FirstBrowserProfileLayout.setStretch(0, 40)
        self.FirstBrowserProfileLayout.setStretch(1, 60)
        self.FirstBrowserVerticalLayout.addLayout(self.FirstBrowserProfileLayout)
        self.FirstBrowserDBFoundLayout = QtGui.QHBoxLayout()
        self.FirstBrowserDBFoundLayout.setObjectName(_fromUtf8("FirstBrowserDBFoundLayout"))
        self.StaticRESInfo = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticRESInfo.setObjectName(_fromUtf8("StaticRESInfo"))
        self.FirstBrowserDBFoundLayout.addWidget(self.StaticRESInfo)
        self.FirstBrowserRESLabel = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.FirstBrowserRESLabel.setObjectName(_fromUtf8("FirstBrowserRESLabel"))
        self.FirstBrowserDBFoundLayout.addWidget(self.FirstBrowserRESLabel)
        self.FirstBrowserDBFoundLayout.setStretch(0, 40)
        self.FirstBrowserDBFoundLayout.setStretch(1, 60)
        self.FirstBrowserVerticalLayout.addLayout(self.FirstBrowserDBFoundLayout)
        self.FirstBrowserLayout.addLayout(self.FirstBrowserVerticalLayout)
        self.BrowseerPickerLayout.addLayout(self.FirstBrowserLayout)
        self.StaticBrowserDividerLine = QtGui.QFrame(self.BackupRestoreMigrateTab)
        self.StaticBrowserDividerLine.setFrameShape(QtGui.QFrame.VLine)
        self.StaticBrowserDividerLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.StaticBrowserDividerLine.setObjectName(_fromUtf8("StaticBrowserDividerLine"))
        self.BrowseerPickerLayout.addWidget(self.StaticBrowserDividerLine)
        self.SecondBrowserLayout = QtGui.QHBoxLayout()
        self.SecondBrowserLayout.setObjectName(_fromUtf8("SecondBrowserLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.StaticSecondBrowserLabel = QtGui.QLabel(self.BackupRestoreMigrateTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.StaticSecondBrowserLabel.setFont(font)
        self.StaticSecondBrowserLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StaticSecondBrowserLabel.setObjectName(_fromUtf8("StaticSecondBrowserLabel"))
        self.verticalLayout.addWidget(self.StaticSecondBrowserLabel)
        self.SecondBrowserNameLayout = QtGui.QHBoxLayout()
        self.SecondBrowserNameLayout.setObjectName(_fromUtf8("SecondBrowserNameLayout"))
        self.StaticBrowserName_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticBrowserName_2.setObjectName(_fromUtf8("StaticBrowserName_2"))
        self.SecondBrowserNameLayout.addWidget(self.StaticBrowserName_2)
        self.cboSecondBrowser = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboSecondBrowser.setObjectName(_fromUtf8("cboSecondBrowser"))
        self.SecondBrowserNameLayout.addWidget(self.cboSecondBrowser)
        self.SecondBrowserNameLayout.setStretch(0, 40)
        self.SecondBrowserNameLayout.setStretch(1, 60)
        self.verticalLayout.addLayout(self.SecondBrowserNameLayout)
        self.SecondBrowserProfileLayout = QtGui.QHBoxLayout()
        self.SecondBrowserProfileLayout.setObjectName(_fromUtf8("SecondBrowserProfileLayout"))
        self.StaticProfileName_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticProfileName_2.setObjectName(_fromUtf8("StaticProfileName_2"))
        self.SecondBrowserProfileLayout.addWidget(self.StaticProfileName_2)
        self.cboSecondBrowserProfile = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboSecondBrowserProfile.setObjectName(_fromUtf8("cboSecondBrowserProfile"))
        self.SecondBrowserProfileLayout.addWidget(self.cboSecondBrowserProfile)
        self.SecondBrowserProfileLayout.setStretch(0, 40)
        self.SecondBrowserProfileLayout.setStretch(1, 60)
        self.verticalLayout.addLayout(self.SecondBrowserProfileLayout)
        self.SecondBrowserDBFoundLayout = QtGui.QHBoxLayout()
        self.SecondBrowserDBFoundLayout.setObjectName(_fromUtf8("SecondBrowserDBFoundLayout"))
        self.StaticRESInfo_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticRESInfo_2.setObjectName(_fromUtf8("StaticRESInfo_2"))
        self.SecondBrowserDBFoundLayout.addWidget(self.StaticRESInfo_2)
        self.SecondBrowserRESLabel = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.SecondBrowserRESLabel.setObjectName(_fromUtf8("SecondBrowserRESLabel"))
        self.SecondBrowserDBFoundLayout.addWidget(self.SecondBrowserRESLabel)
        self.SecondBrowserDBFoundLayout.setStretch(0, 40)
        self.SecondBrowserDBFoundLayout.setStretch(1, 60)
        self.verticalLayout.addLayout(self.SecondBrowserDBFoundLayout)
        self.SecondBrowserLayout.addLayout(self.verticalLayout)
        self.BrowseerPickerLayout.addLayout(self.SecondBrowserLayout)
        self.BrowseerPickerLayout.setStretch(0, 45)
        self.BrowseerPickerLayout.setStretch(1, 5)
        self.BrowseerPickerLayout.setStretch(2, 45)
        self.MainContentLayout.addLayout(self.BrowseerPickerLayout)
        self.StaticBrowserFeaturesLine = QtGui.QFrame(self.BackupRestoreMigrateTab)
        self.StaticBrowserFeaturesLine.setFrameShape(QtGui.QFrame.HLine)
        self.StaticBrowserFeaturesLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.StaticBrowserFeaturesLine.setObjectName(_fromUtf8("StaticBrowserFeaturesLine"))
        self.MainContentLayout.addWidget(self.StaticBrowserFeaturesLine)
        self.labelMessage = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.labelMessage.setEnabled(True)
        self.labelMessage.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.labelMessage.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName(_fromUtf8("labelMessage"))
        self.MainContentLayout.addWidget(self.labelMessage)
        self.ApplicationActionsLayout = QtGui.QHBoxLayout()
        self.ApplicationActionsLayout.setObjectName(_fromUtf8("ApplicationActionsLayout"))
        self.BackupsLayout = QtGui.QVBoxLayout()
        self.BackupsLayout.setObjectName(_fromUtf8("BackupsLayout"))
        self.StaticLabelMigrating = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelMigrating.setObjectName(_fromUtf8("StaticLabelMigrating"))
        self.BackupsLayout.addWidget(self.StaticLabelMigrating)
        self.btnFirstToSecond = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnFirstToSecond.setEnabled(False)
        self.btnFirstToSecond.setObjectName(_fromUtf8("btnFirstToSecond"))
        self.BackupsLayout.addWidget(self.btnFirstToSecond)
        self.btnSecondToFirst = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnSecondToFirst.setEnabled(False)
        self.btnSecondToFirst.setObjectName(_fromUtf8("btnSecondToFirst"))
        self.BackupsLayout.addWidget(self.btnSecondToFirst)
        self.StaticDivider = QtGui.QFrame(self.BackupRestoreMigrateTab)
        self.StaticDivider.setFrameShape(QtGui.QFrame.HLine)
        self.StaticDivider.setFrameShadow(QtGui.QFrame.Sunken)
        self.StaticDivider.setObjectName(_fromUtf8("StaticDivider"))
        self.BackupsLayout.addWidget(self.StaticDivider)
        self.StaticLabelBackups_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelBackups_2.setObjectName(_fromUtf8("StaticLabelBackups_2"))
        self.BackupsLayout.addWidget(self.StaticLabelBackups_2)
        self.btnBackupFirst = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnBackupFirst.setEnabled(False)
        self.btnBackupFirst.setObjectName(_fromUtf8("btnBackupFirst"))
        self.BackupsLayout.addWidget(self.btnBackupFirst)
        self.btnBackupSecond = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnBackupSecond.setEnabled(False)
        self.btnBackupSecond.setObjectName(_fromUtf8("btnBackupSecond"))
        self.BackupsLayout.addWidget(self.btnBackupSecond)
        self.btnRestoreToFirst = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnRestoreToFirst.setEnabled(False)
        self.btnRestoreToFirst.setObjectName(_fromUtf8("btnRestoreToFirst"))
        self.BackupsLayout.addWidget(self.btnRestoreToFirst)
        self.btnRestoreToSecond = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnRestoreToSecond.setEnabled(False)
        self.btnRestoreToSecond.setObjectName(_fromUtf8("btnRestoreToSecond"))
        self.BackupsLayout.addWidget(self.btnRestoreToSecond)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.BackupsLayout.addItem(spacerItem)
        self.StaticLabelVersion = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelVersion.setObjectName(_fromUtf8("StaticLabelVersion"))
        self.BackupsLayout.addWidget(self.StaticLabelVersion)
        self.ApplicationActionsLayout.addLayout(self.BackupsLayout)
        self.MainFeaturesLayout = QtGui.QVBoxLayout()
        self.MainFeaturesLayout.setObjectName(_fromUtf8("MainFeaturesLayout"))
        self.StaticLabelBackups = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelBackups.setObjectName(_fromUtf8("StaticLabelBackups"))
        self.MainFeaturesLayout.addWidget(self.StaticLabelBackups)
        self.listBackups = QtGui.QListWidget(self.BackupRestoreMigrateTab)
        self.listBackups.setObjectName(_fromUtf8("listBackups"))
        item = QtGui.QListWidgetItem()
        self.listBackups.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listBackups.addItem(item)
        self.MainFeaturesLayout.addWidget(self.listBackups)
        self.ApplicationActionsLayout.addLayout(self.MainFeaturesLayout)
        self.ApplicationActionsLayout.setStretch(0, 60)
        self.ApplicationActionsLayout.setStretch(1, 40)
        self.MainContentLayout.addLayout(self.ApplicationActionsLayout)
        self.MainContentLayout.setStretch(0, 30)
        self.MainContentLayout.setStretch(3, 70)
        self.verticalLayout_2.addLayout(self.MainContentLayout)
        self.MainTabWidget.addTab(self.BackupRestoreMigrateTab, _fromUtf8(""))
        self.SettingsTab = QtGui.QWidget()
        self.SettingsTab.setObjectName(_fromUtf8("SettingsTab"))
        self.MainTabWidget.addTab(self.SettingsTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.MainTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RESTool - Development Version", None))
        self.StaticFirstBrowserLabel.setText(_translate("MainWindow", "First Browser", None))
        self.StaticBrowserName.setText(_translate("MainWindow", "Browser Name:", None))
        self.StaticProfileName.setText(_translate("MainWindow", "Profile Name:", None))
        self.StaticRESInfo.setText(_translate("MainWindow", "RES DB found:", None))
        self.FirstBrowserRESLabel.setText(_translate("MainWindow", "N/A", None))
        self.StaticSecondBrowserLabel.setText(_translate("MainWindow", "Second Browser", None))
        self.StaticBrowserName_2.setText(_translate("MainWindow", "Browser Name:", None))
        self.StaticProfileName_2.setText(_translate("MainWindow", "Profile Name:", None))
        self.StaticRESInfo_2.setText(_translate("MainWindow", "RES DB found:", None))
        self.SecondBrowserRESLabel.setText(_translate("MainWindow", "N/A", None))
        self.labelMessage.setText(_translate("MainWindow", "<html><head/><body><p>Warning message</p></body></html>", None))
        self.StaticLabelMigrating.setText(_translate("MainWindow", "Migrating existing data", None))
        self.btnFirstToSecond.setText(_translate("MainWindow", "First browser to the second browser", None))
        self.btnSecondToFirst.setText(_translate("MainWindow", "Second browser to the first browser", None))
        self.StaticLabelBackups_2.setText(_translate("MainWindow", "RES database backups", None))
        self.btnBackupFirst.setText(_translate("MainWindow", "Backup first browser", None))
        self.btnBackupSecond.setText(_translate("MainWindow", "Backup second browser", None))
        self.btnRestoreToFirst.setText(_translate("MainWindow", "Restore selected backup to the first browser", None))
        self.btnRestoreToSecond.setText(_translate("MainWindow", "Restore selected backup to the second browser", None))
        self.StaticLabelVersion.setText(_translate("MainWindow", "<html><head/><body><p>Version 0.2dev - GitHub: <a href=\"https://github.com/Nikola-K/RESTool\"><span style=\" text-decoration: underline; color:#0000ff;\">Nikola-K/RESTool</span></a></p></body></html>", None))
        self.StaticLabelBackups.setText(_translate("MainWindow", "Available Backups", None))
        __sortingEnabled = self.listBackups.isSortingEnabled()
        self.listBackups.setSortingEnabled(False)
        item = self.listBackups.item(0)
        item.setText(_translate("MainWindow", "Chrome 2015-01-01-2200.backup", None))
        item = self.listBackups.item(1)
        item.setText(_translate("MainWindow", "Firefox 2015-12-31-1958.backup", None))
        self.listBackups.setSortingEnabled(__sortingEnabled)
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.BackupRestoreMigrateTab), _translate("MainWindow", "RESTool", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.SettingsTab), _translate("MainWindow", "Settings", None))

