# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RESTool/ui/design_v2.ui'
#
# Created: Sat May 16 09:17:10 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(583, 472)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.MainTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.MainTabWidget.setObjectName(_fromUtf8("MainTabWidget"))
        self.BackupRestoreMigrateTab = QtGui.QWidget()
        self.BackupRestoreMigrateTab.setObjectName(_fromUtf8("BackupRestoreMigrateTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.BackupRestoreMigrateTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MainContentLayout = QtGui.QVBoxLayout()
        self.MainContentLayout.setObjectName(_fromUtf8("MainContentLayout"))
        self.BrowseerPickerLayout = QtGui.QHBoxLayout()
        self.BrowseerPickerLayout.setObjectName(_fromUtf8("BrowseerPickerLayout"))
        self.FirstBrowserLayout = QtGui.QFormLayout()
        self.FirstBrowserLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.FirstBrowserLayout.setObjectName(_fromUtf8("FirstBrowserLayout"))
        self.StaticLabelInfo = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelInfo.setObjectName(_fromUtf8("StaticLabelInfo"))
        self.FirstBrowserLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.StaticLabelInfo)
        self.StaticBrowserName = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticBrowserName.setObjectName(_fromUtf8("StaticBrowserName"))
        self.FirstBrowserLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.StaticBrowserName)
        self.cboFirstBrowser = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboFirstBrowser.setObjectName(_fromUtf8("cboFirstBrowser"))
        self.FirstBrowserLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cboFirstBrowser)
        self.StaticProfileName = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticProfileName.setObjectName(_fromUtf8("StaticProfileName"))
        self.FirstBrowserLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.StaticProfileName)
        self.cboFirstBrowserProfile = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboFirstBrowserProfile.setObjectName(_fromUtf8("cboFirstBrowserProfile"))
        self.FirstBrowserLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cboFirstBrowserProfile)
        self.StaticRESInfo = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticRESInfo.setObjectName(_fromUtf8("StaticRESInfo"))
        self.FirstBrowserLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.StaticRESInfo)
        self.FirstBrowserRESLabel = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.FirstBrowserRESLabel.setObjectName(_fromUtf8("FirstBrowserRESLabel"))
        self.FirstBrowserLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.FirstBrowserRESLabel)
        self.BrowseerPickerLayout.addLayout(self.FirstBrowserLayout)
        self.StaticBrowserDividerLine = QtGui.QFrame(self.BackupRestoreMigrateTab)
        self.StaticBrowserDividerLine.setFrameShape(QtGui.QFrame.VLine)
        self.StaticBrowserDividerLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.StaticBrowserDividerLine.setObjectName(_fromUtf8("StaticBrowserDividerLine"))
        self.BrowseerPickerLayout.addWidget(self.StaticBrowserDividerLine)
        self.SecondBrowserLayout = QtGui.QFormLayout()
        self.SecondBrowserLayout.setObjectName(_fromUtf8("SecondBrowserLayout"))
        self.StaticLabelInfo_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelInfo_2.setObjectName(_fromUtf8("StaticLabelInfo_2"))
        self.SecondBrowserLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.StaticLabelInfo_2)
        self.StaticBrowserName_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticBrowserName_2.setObjectName(_fromUtf8("StaticBrowserName_2"))
        self.SecondBrowserLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.StaticBrowserName_2)
        self.StaticProfileName_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticProfileName_2.setObjectName(_fromUtf8("StaticProfileName_2"))
        self.SecondBrowserLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.StaticProfileName_2)
        self.StaticRESInfo_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticRESInfo_2.setObjectName(_fromUtf8("StaticRESInfo_2"))
        self.SecondBrowserLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.StaticRESInfo_2)
        self.cboSecondBrowser = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboSecondBrowser.setObjectName(_fromUtf8("cboSecondBrowser"))
        self.SecondBrowserLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cboSecondBrowser)
        self.cboSecondBrowserProfile = QtGui.QComboBox(self.BackupRestoreMigrateTab)
        self.cboSecondBrowserProfile.setObjectName(_fromUtf8("cboSecondBrowserProfile"))
        self.SecondBrowserLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cboSecondBrowserProfile)
        self.SecondBrowserRESLabel = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.SecondBrowserRESLabel.setObjectName(_fromUtf8("SecondBrowserRESLabel"))
        self.SecondBrowserLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.SecondBrowserRESLabel)
        self.BrowseerPickerLayout.addLayout(self.SecondBrowserLayout)
        self.BrowseerPickerLayout.setStretch(0, 50)
        self.BrowseerPickerLayout.setStretch(2, 50)
        self.MainContentLayout.addLayout(self.BrowseerPickerLayout)
        self.StaticBrowserFeaturesLine = QtGui.QFrame(self.BackupRestoreMigrateTab)
        self.StaticBrowserFeaturesLine.setFrameShape(QtGui.QFrame.HLine)
        self.StaticBrowserFeaturesLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.StaticBrowserFeaturesLine.setObjectName(_fromUtf8("StaticBrowserFeaturesLine"))
        self.MainContentLayout.addWidget(self.StaticBrowserFeaturesLine)
        self.labelMessage = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.labelMessage.setEnabled(True)
        self.labelMessage.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.labelMessage.setFrameShape(QtGui.QFrame.NoFrame)
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName(_fromUtf8("labelMessage"))
        self.MainContentLayout.addWidget(self.labelMessage)
        self.ApplicationActionsLayout = QtGui.QHBoxLayout()
        self.ApplicationActionsLayout.setObjectName(_fromUtf8("ApplicationActionsLayout"))
        self.BackupsLayout = QtGui.QVBoxLayout()
        self.BackupsLayout.setObjectName(_fromUtf8("BackupsLayout"))
        self.StaticLabelMigrating = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelMigrating.setObjectName(_fromUtf8("StaticLabelMigrating"))
        self.BackupsLayout.addWidget(self.StaticLabelMigrating)
        self.btnFirstToSecond = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnFirstToSecond.setEnabled(False)
        self.btnFirstToSecond.setObjectName(_fromUtf8("btnFirstToSecond"))
        self.BackupsLayout.addWidget(self.btnFirstToSecond)
        self.btnSecondToFirst = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnSecondToFirst.setEnabled(False)
        self.btnSecondToFirst.setObjectName(_fromUtf8("btnSecondToFirst"))
        self.BackupsLayout.addWidget(self.btnSecondToFirst)
        self.StaticDivider = QtGui.QFrame(self.BackupRestoreMigrateTab)
        self.StaticDivider.setFrameShape(QtGui.QFrame.HLine)
        self.StaticDivider.setFrameShadow(QtGui.QFrame.Sunken)
        self.StaticDivider.setObjectName(_fromUtf8("StaticDivider"))
        self.BackupsLayout.addWidget(self.StaticDivider)
        self.StaticLabelBackups_2 = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelBackups_2.setObjectName(_fromUtf8("StaticLabelBackups_2"))
        self.BackupsLayout.addWidget(self.StaticLabelBackups_2)
        self.btnBackupFirst = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnBackupFirst.setEnabled(False)
        self.btnBackupFirst.setObjectName(_fromUtf8("btnBackupFirst"))
        self.BackupsLayout.addWidget(self.btnBackupFirst)
        self.btnBackupSecond = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnBackupSecond.setEnabled(False)
        self.btnBackupSecond.setObjectName(_fromUtf8("btnBackupSecond"))
        self.BackupsLayout.addWidget(self.btnBackupSecond)
        self.btnRestoreToFirst = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnRestoreToFirst.setEnabled(False)
        self.btnRestoreToFirst.setObjectName(_fromUtf8("btnRestoreToFirst"))
        self.BackupsLayout.addWidget(self.btnRestoreToFirst)
        self.btnRestoreToSecond = QtGui.QPushButton(self.BackupRestoreMigrateTab)
        self.btnRestoreToSecond.setEnabled(False)
        self.btnRestoreToSecond.setObjectName(_fromUtf8("btnRestoreToSecond"))
        self.BackupsLayout.addWidget(self.btnRestoreToSecond)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.BackupsLayout.addItem(spacerItem)
        self.StaticLabelVersion = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelVersion.setObjectName(_fromUtf8("StaticLabelVersion"))
        self.BackupsLayout.addWidget(self.StaticLabelVersion)
        self.ApplicationActionsLayout.addLayout(self.BackupsLayout)
        self.MainFeaturesLayout = QtGui.QVBoxLayout()
        self.MainFeaturesLayout.setObjectName(_fromUtf8("MainFeaturesLayout"))
        self.StaticLabelBackups = QtGui.QLabel(self.BackupRestoreMigrateTab)
        self.StaticLabelBackups.setObjectName(_fromUtf8("StaticLabelBackups"))
        self.MainFeaturesLayout.addWidget(self.StaticLabelBackups)
        self.listBackups = QtGui.QListWidget(self.BackupRestoreMigrateTab)
        self.listBackups.setObjectName(_fromUtf8("listBackups"))
        item = QtGui.QListWidgetItem()
        self.listBackups.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listBackups.addItem(item)
        self.MainFeaturesLayout.addWidget(self.listBackups)
        self.ApplicationActionsLayout.addLayout(self.MainFeaturesLayout)
        self.ApplicationActionsLayout.setStretch(0, 60)
        self.ApplicationActionsLayout.setStretch(1, 40)
        self.MainContentLayout.addLayout(self.ApplicationActionsLayout)
        self.MainContentLayout.setStretch(0, 30)
        self.MainContentLayout.setStretch(3, 70)
        self.verticalLayout_2.addLayout(self.MainContentLayout)
        self.MainTabWidget.addTab(self.BackupRestoreMigrateTab, _fromUtf8(""))
        self.SettingsTab = QtGui.QWidget()
        self.SettingsTab.setObjectName(_fromUtf8("SettingsTab"))
        self.MainTabWidget.addTab(self.SettingsTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.MainTabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RESTool - Development Version", None))
        self.StaticLabelInfo.setText(_translate("MainWindow", "First Browser:", None))
        self.StaticBrowserName.setText(_translate("MainWindow", "Browser Name:", None))
        self.StaticProfileName.setText(_translate("MainWindow", "Profile Name", None))
        self.StaticRESInfo.setText(_translate("MainWindow", "RES DB found:", None))
        self.FirstBrowserRESLabel.setText(_translate("MainWindow", "N/A", None))
        self.StaticLabelInfo_2.setText(_translate("MainWindow", "Second Browser:", None))
        self.StaticBrowserName_2.setText(_translate("MainWindow", "Browser Name:", None))
        self.StaticProfileName_2.setText(_translate("MainWindow", "Profile Name:", None))
        self.StaticRESInfo_2.setText(_translate("MainWindow", "RES DB found:", None))
        self.SecondBrowserRESLabel.setText(_translate("MainWindow", "N/A", None))
        self.labelMessage.setText(_translate("MainWindow", "<html><head/><body><p>Warning message</p></body></html>", None))
        self.StaticLabelMigrating.setText(_translate("MainWindow", "Migrating existing data", None))
        self.btnFirstToSecond.setText(_translate("MainWindow", "First browser to the second browser", None))
        self.btnSecondToFirst.setText(_translate("MainWindow", "Second browser to the first browser", None))
        self.StaticLabelBackups_2.setText(_translate("MainWindow", "RES database backups", None))
        self.btnBackupFirst.setText(_translate("MainWindow", "Backup first browser", None))
        self.btnBackupSecond.setText(_translate("MainWindow", "Backup second browser", None))
        self.btnRestoreToFirst.setText(_translate("MainWindow", "Restore selected backup to the first browser", None))
        self.btnRestoreToSecond.setText(_translate("MainWindow", "Restore selected backup to the second browser", None))
        self.StaticLabelVersion.setText(_translate("MainWindow", "<html><head/><body><p>Version 0.2dev - GitHub: <a href=\"https://github.com/Nikola-K/RESTool\"><span style=\" text-decoration: underline; color:#0000ff;\">Nikola-K/RESTool</span></a></p></body></html>", None))
        self.StaticLabelBackups.setText(_translate("MainWindow", "Available Backups", None))
        __sortingEnabled = self.listBackups.isSortingEnabled()
        self.listBackups.setSortingEnabled(False)
        item = self.listBackups.item(0)
        item.setText(_translate("MainWindow", "Chrome 2015-01-01-2200.backup", None))
        item = self.listBackups.item(1)
        item.setText(_translate("MainWindow", "Firefox 2015-12-31-1958.backup", None))
        self.listBackups.setSortingEnabled(__sortingEnabled)
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.BackupRestoreMigrateTab), _translate("MainWindow", "Backup/Restore/Migrate", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.SettingsTab), _translate("MainWindow", "Settings", None))

